POST localhost:4000/auth/signup
Content-Type: application/json

{"name": "Bruce Wayne","email": "bruce@wayne.com","password": "IamBatman"}
###
POST localhost:4000/auth/login
Content-Type: application/json

{"email":"bruce@wayne.com", "password":"IamBatman"}
###
POST localhost:4000/auth/signup
Content-Type: application/json

{"name": "Tony Stark","email": "tony@stark.com","password": "IamIronman"}